import SignInPage from "../support/pageObjects/SignInPage.js"
import TermsAndConditionsPage from "../support/pageObjects/TermsAndConditionsPage"
import HomePage from "../support/pageObjects/HomePage.js"
import PassportPage from "../support/pageObjects/PassportPage.js"
import Navigation from "../support/pageObjects/Navigation.js"

describe('Test Suite', function()
{
    const signInPage = new SignInPage()
    const termsAndConditionsPage = new TermsAndConditionsPage()
    const homePage = new HomePage()
    const navigation = new Navigation()
    const passportPage = new PassportPage()

    beforeEach(function()
    {
        cy.fixture('example').then(function(data)
        {
            this.data=data
        })
    })

    it('Passport form fill test', function()
    {
        cy.visit(Cypress.env('url') + 'signin')
        signInPage.getUsernameTBox().type(this.data.signInUserName)
        signInPage.getPasswordTBox().type(this.data.signInPassword)
        signInPage.getContinueButton().click()
        signInPage.getVerificationCodeTBox().should('be.visible').wait(15000)
        signInPage.getSignInButton().click()
        cy.url().should('include', '/termsconditions')
        termsAndConditionsPage.getAcceptButton().click()
        homePage.getHomePageTitle().should('have.text', this.data.homePageTitleEn)
        cy.url().should('include', '/home')
        cy.log("User successfully logged into VAC Portal and navigated to Home page")
        homePage.getNewApplicationLink().click().then (function()
        {
            cy.wait(5000)
            cy.url().should('include', '/client/general/personal-details')
        })
        navigation.getNavbarPassport().click()
        passportPage.getPassportHeader().should('have.text', this.data.passportPageHeader )
        passportPage.getPassportNumberTBox().clear({force : true}).type(this.data.passportNumber)
        passportPage.getCountryDropDown().type('C')
        passportPage.getCountryIssueSelect().click()
        passportPage.getIssueYearDropDown().clear().type(this.data.issueYear)
        passportPage.getIssueMonthDropDown().clear().type(this.data.issueMonth)
        passportPage.getIssueDayDropDown().clear().type(this.data.issueDay)
        passportPage.getExpiryYearDropDown().clear().type(this.data.expiryYear)
        passportPage.getExpiryMonthDropDown().clear().type(this.data.expiryMonth)
        passportPage.getExpiryDayDropDown().clear().type(this.data.expiryDay)
        passportPage.getPassportTypeDropDown().click()
        passportPage.getDiplomaticTypeSelect().click()
        passportPage.getTaiwanRadio().click()
        passportPage.getIsraelRadio().click()
        passportPage.getNationalIDRadio().click()
        passportPage.getNationalIDDocumentNumberTBox().clear().type(this.data.nationalIDDocumentNumber)
        passportPage.getNationalIDCountryIssueDropDown().click()
        passportPage.getNationalIDCountrySelect().click()
        passportPage.getNationalIDIssueYearDropDown().clear().type(this.data.issueYear)
        passportPage.getNationalIDIssueMonthDropDown().clear().type(this.data.issueMonth)
        passportPage.getNationalIDCIssueDayDropDown().clear().type(this.data.issueDay)
        passportPage.getNationalIDExpiryYearDropDown().clear().type(this.data.expiryYear)
        passportPage.getNationalIDExpiryMonthDropDown().clear().type(this.data.expiryMonth)
        passportPage.getNationalIDExpiryDayDropDown().clear().type(this.data.expiryDay)
        passportPage.getUSPRStatusRadio().click()
        passportPage.getUSPRDocumentNumberTBox().clear().type(this.data.usPRDocumentNumber)
        passportPage.getUSPRExpiryYearDropDown().clear().type(this.data.expiryYear)
        passportPage.getUSPRExpiryMonthDropDown().clear().type(this.data.expiryMonth)
        passportPage.getUSPRxpiryDayDropDown().clear().type(this.data.expiryDay)
        passportPage.getSaveAndContinueButton().click()
        cy.url().should('include','/visit-details')
        cy.log("Passport Form is successfully completed")
    })
})
